spring:
    application:
        name: auth-service
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:~/auth-service-db
        username: sa
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
server:
    port: 8083
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
    instance:
        preferIpAddress: true
com:
    marcpinol:
        jwt:
            secret: QHsyZFY/O11WNnRUTVEzeTokQ1JDUnBpR3RwIUVGKHA=
            valid-token-time: 36_00