spring:
  application:
    name: auth-service
  cloud:
    config:
      fail-fast: true
      username: root
      password: s3cr3t
      retry:
        max-attempts: 10
  config:
    import: optional:configserver:http://localhost:8082
  profiles:
    active: development